server:
  port: 8090
  session-timeout: 60

security.basic.enabled: false
endpoints.shutdown.enabled: true

spring.profiles.active: proddb
spring.profiles.include: security, mailon

plataforma:
  ayuda-service:
    hoursToWaitRegister: 1
    registerAvailablePeruser: 2
  url.confirm.token: ${URL_CONFIRM_TOKEN}
  url.change.password: ${URL_CHANGE_PASSWORD}

---
spring:
  profiles: security

jwt:
  header: X-Auth-Token
  secret: mySecret
  expiration: 604800

---
spring:
  profiles: proddb
  datasource:
    url: ${SECRET_DB_URL}
    username: ${SECRET_DB_USERNAME}
    password: ${SECRET_DB_PASSWORD}
  jpa:
    hibernate.ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        default_schema: ${SECRET_DB_SCHEMA}
        hibernate.show_sql: false
        format_sql: false

---
spring:
  profiles: localdb
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate.ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console

plataforma.url.confirm.token: http://localhost:4200/#/confirmacion
plataforma.url.change.password: http://localhost:8090/api/v1/public/users/change_password
---
spring:
  profiles: mailon

mail:
  host: smtp.gmail.com
  port: 587
  username: ${SECRET_EMAIL_USERNAME}
  password: ${SECRET_EMAIL_PASSWORD}
  from.default: notificacion@plataformacovid19.mx
  to.default: notificacion@plataformacovid19.mx
  subject.default: Notificacion PMC
  transport.protocol: smtp
  debug: on
  smtp:
    auth: true
    starttls.enable: true
